### ISSUE TITLE
Error: Module version mismatch. Expected 48, got 49.

### ISSUE THREAD

**Issue by Thomas101** [LinusU/node-alias#12]
Hi,

I'm getting an error when trying to require the module with node 6.3.0 and 6.4.0.

```
MacBook-Pro:wmail Tom$ node
> require('macos-alias')
Error: Module version mismatch. Expected 48, got 49.
    at Error (native)
    at Object.Module._extensions..node (module.js:583:18)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/Tom/GitHub/wmail/node_modules/macos-alias/lib/create.js:7:13)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
```

I've tried removing node_modules and doing `npm cache clean`. I've tried running `node-gyp rebuild` in the directory but to no avail. Do you have any suggestions?

Thanks!

**Comment by Thomas101** [comment]
Just a quick update `npm rebuild` seemed to get it running again...

**Comment by LinusU** [comment]
`npm rebuild` is the correct solution 👍
