### ISSUE TITLE
Xcodebuild error when installing.

### ISSUE THREAD

**Issue by Meadowcottage** [LinusU/node-alias#15]
Having an issue when installing `create-dmg` and issues seems to being caused by `macos-alias`.
Xcode and Xcode CLI tools already currently installed.
```
➜  Desktop npm i -g create-dmg
/usr/local/bin/create-dmg -> /usr/local/lib/node_modules/create-dmg/cli.js

> macos-alias@0.2.11 install /usr/local/lib/node_modules/create-dmg/node_modules/macos-alias
> node-gyp rebuild

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

No receipt for 'com.apple.pkg.CLTools_Executables' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLILeo' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLI' found at '/'.

gyp: No Xcode or CLT version detected!
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:336:16)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:197:12)
gyp ERR! System Darwin 17.0.0
gyp ERR! command "/usr/local/Cellar/node/8.1.0_1/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/create-dmg/node_modules/macos-alias
gyp ERR! node -v v8.1.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! macos-alias@0.2.11 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the macos-alias@0.2.11 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/meadowcottage/.npm/_logs/2017-06-22T13_20_18_842Z-debug.log
```

**Comment by LinusU** [comment]
Unfortunately this is a bit poorly documented, but you need to install XCode and the command line tools. More info: https://github.com/nodejs/node-gyp#on-mac-os-x

**Comment by Meadowcottage** [comment]
My mistake. I had Xcode and Xcode CLI tools installed. But I had both version 8.3.3 and version 9.0 of the CLI tools installed and CLI tools location was yet to be told what version to use.

**Comment by anothermh** [comment]
Should anyone else experience this and need to know how to apply the solution described by @NuroDev, it's done by opening Xcode > Preferences > Locations > Command Line Tools.

Ran into the same issue using Catalina beta and Xcode 10.2.1.
